In [2]:
import pandas as pd
import numpy as np

Este notebook é um extra utilizado apenas para testar a biblioteca Plotly, que cria graficos (e diversas outras coisas) interativas
-----------------------------------------------------------------------------------------------------------------------------------

In [110]:
import plotly as py
import plotly.graph_objs as go
py.tools.set_credentials_file(username='gian.lepear', api_key='zXql2DKxn9tq4DwoqwRt')

In [124]:
df = pd.read_excel('4-GoogleLatLng/GoogleLatLng.xlsx')

In [125]:
df = df[['bairro', 'categoria', 'preco']]
df.groupby(['categoria'])['preco'].count()

categoria
Aluguel de quartos              13
Apartamentos                   245
Casas                          147
Indústria e comércio            69
Temporada                        1
Terrenos, sítios e fazendas     25
Name: preco, dtype: int64

In [133]:
df_casa = df[df['categoria'] == 'Casas']
df_casa = df_casa[['bairro', 'preco']]
df_casa = df_casa[df_casa['preco'] > 100000]
df_casa.reset_index(drop=True, inplace=True)

In [135]:
df_casa

                           bairro     preco
0                    Vila Granada    560000
1          Parque Cruzeiro do Sul    400000
2          Parque Cruzeiro do Sul    400000
3                  Jardim Maringá    350000
4                       Vila Bela    398000
5                Vila S Francisco    495000
6              Chácara Califórnia    425000
7                    Vila Taquari    240000
8              Cidade Continental    470000
9               Cidade Mãe do Céu    350000
10                   Vila Granada    560000
11         Parque Cruzeiro do Sul    400000
12         Parque Cruzeiro do Sul    400000
13                 Jardim Maringá    350000
14                      Vila Bela    398000
15               Vila S Francisco    495000
16             Chácara Califórnia    425000
17                   Vila Taquari    240000
18             Cidade Continental    470000
19              Cidade Mãe do Céu    350000
20             Jardim São Nicolau    230000
21            Cj Hab A E Carvalho    295000
22                       Itaquera    290000
23              Cidade Tiradentes    450000
24                       Vila Ind    420000
25                  Vila Prudente    430000
26                        Vila Ré    990000
27                Vila Califórnia    247000
28                     Vila Norma    350000
29  Jardim Nossa Senhora do Carmo    670000
..                            ...       ...
54              Vila Gomes Cardim    350000
55                     Vila Jacuí    350000
56                          Mooca    750000
57             Chácara Belenzinho    420000
58                    Vila Carrão  16000003
59              Jardim Guaianazes    250000
60                Jardim Colonial    480000
61                    Vila Carrão    450000
62                          Mooca    650000
63                     Vila Jacuí    299000
64                 Vila Carmosina    240000
65                 C A E Carvalho    160000
66               Jardim Imperador    480000
67  Jardim Nossa Senhora do Carmo    950000
68                Jardim Panorama   2200000
69                     Belenzinho    990000
70                          Mooca   1200000
71                       Vila Ema    600000
72               Cidade Patriarca    410000
73                          Mooca    330000
74                  Alto da Mooca    475000
75         Parque Cruzeiro do Sul    400000
76                           Brás    685000
77         Parque Cruzeiro do Sul    400000
78                   Vila Marieta    780000
79                       Itaquera    229000
80                          Mooca    300000
81               Vila Santa Clara    700000
82                        Tatuapé   2000000
83                Penha De França    349500

[84 rows x 2 columns]

In [136]:
#cria um data frame com a soma dos precos dos municipios
df_casa_soma = df_casa.groupby(['bairro'], as_index=False)['preco'].sum()
df_casa_soma.columns= ['bairro', 'preco_soma']
#media
df_casa_media = df_casa.groupby(['bairro'], as_index=False)['preco'].mean()
df_casa_media.columns= ['bairro', 'preco_media']
#numero de ocorrencias
df_casa_count = df_casa.groupby(['bairro'],as_index=False)['preco'].count()
df_casa_count.columns= ['bairro', 'count']

In [137]:
df_agrupa = df_casa_soma.merge(df_casa_media, on='bairro')
df_agrupa = df_agrupa.merge(df_casa_count, on='bairro')

In [142]:
df_agrupa = df_agrupa.sort_values('preco_media', ascending=False).reset_index(drop=True)
df_agrupa.head()

                          bairro  preco_soma  preco_media  count
0                    Vila Carrão    16450003    8225001.5      2
1                Jardim Panorama     2200000    2200000.0      1
2                        Tatuapé     2000000    2000000.0      1
3                     Belenzinho      990000     990000.0      1
4  Jardim Nossa Senhora do Carmo     1620000     810000.0      2

In [143]:
data = [
    go.Bar(
        x=df_agrupa['bairro'].head(),
        y=df_agrupa['preco_media'].head()
    )
]

In [145]:
# IPython notebook
py.plotly.iplot(data, filename='OLX_SP_CASAS_MEDIA_x_BAIRRO', title='SP-CASAS À VENDA SOMA x BAIRRO')

In [146]:
df_agrupa = df_agrupa.sort_values('preco_soma', ascending=False).reset_index(drop=True)
data = [
    go.Bar(
        x=df_agrupa['bairro'].head(),
        y=df_agrupa['preco_soma'].head()
    )
]

In [148]:
# IPython notebook
py.plotly.iplot(data, filename='OLX_SP_CASAS_SOMA_x_BAIRRO', title='SP-CASAS À VENDA SOMA x BAIRRO')

In [149]:
df_agrupa = df_agrupa.sort_values('count', ascending=False).reset_index(drop=True)
data = [
    go.Bar(
        x=df_agrupa['bairro'].head(),
        y=df_agrupa['count'].head()
    )
]

In [150]:
# IPython notebook
py.plotly.iplot(data, filename='OLX_SP_CASAS_NUMERO_x_BAIRRO', title='SP-CASAS À VENDA SOMA x BAIRRO')